### ISSUE TITLE
can't build in xcode7.3.1

### ISSUE THREAD

**Issue by moonrailgun** [uxmstudio/LANScanner#1]
just like following problem
![adsfdasfdaf](https://cloud.githubusercontent.com/assets/6964737/16545242/92ba3e76-4157-11e6-9b74-c3bb87b3b29a.jpg)

**Comment by pushchris** [comment]
Can you get me some more details? What device are you trying to build for? What architecture are you using? What version of iOS is your base version / deployment target? The more information you can get me the better.

**Comment by pushchris** [comment]
I believe the last commit should solve your problem. Reopen the issue if it does not

**Comment by moonrailgun** [comment]
the lastest is usable
and hope to update lastest version to cocoapods.org.
we need this package manager to maintain a available repo version by podfile
thanks:)
