### ISSUE TITLE
Method LANScanner.startScan() gets error 101 due of different network environment

### ISSUE THREAD

**Issue by mxd4n13l0n** [uxmstudio/LANScanner#6]
When trying to integrate the LanScanner pod on a iPad Air 2 simulator I get the error code 101.
Trying to debug the problem I found that the method getLocalAddress() returns nil. Taking a look in the code it seems that the while loop that is looking for the "en0" string on the interface name are not matched. That error was triggered because I might be using an external network card.

What if it could be changed to the following:

```Swift

  let name = String(cString:interface.ifa_name)
  if name..range(of:"en") != nil {
     //...
}

```

Would be glad if you allow me to do a pull request.

Regards,

**Comment by pushchris** [comment]
Feel free to submit a pull request
